### ISSUE TITLE
SVP Core Causing Random Grapic Corruption

### ISSUE THREAD

**Issue by nick3092** [RevQuixo/MegaSD-Bugtracker#16]
At least 3 users have reported that the regular/SVP version of Virtua Racing have random dots showing up in various places.  Most notably in the menu when selecting the racing mode.  This has occurred on model 1s, model 2's, and Mega Sgs.  The ROM CRC was confirmed with one of the affected users to be a known good version of the ROM that works fine for most other people.  The issue seems to be tied to the MegaSD cart itself, as the same cart seems to act up on multiple systems tested by the owner(s).  Forcing the firmware update has not resolved the issue.  The issue occurs over both composite and RGB on a real Genesis.

**Comment by RevQuixo** [comment]
Fixed in Next release

**Comment by RevQuixo** [comment]
In latest build
